package ayrıkYapılarProje2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ErdemÇağrı
 */
public class AyrıkYapılarProje2 extends javax.swing.JFrame {
static String[] third(int iter){   
                 String[] sequence = new String[iter];
                 int[] divisor = new int[iter];   
             divisor[0] = 1;            
for (int i = 1; i < iter; i++) {           
    if (i%2 == 0) {             
        divisor[i] = divisor[i-1] + 2;         
    }            if(i%2 == 1){        
        
        divisor[i] = divisor[i-1] + 3;    
    }    
}              
for (int i = 0; i < iter; i++) {    
    if (i%2 == 0) {            
        sequence[i] = "+1/"+divisor[i]+" ";       
    }            else{          
        sequence[i] = "-1/"+divisor[i]+" ";      
    }        }           
return sequence; 
}
public static double math( double x, int i)
	{	
		if (i == 1)
			return x;
        else;
            return Math.pow(x, i)/factorial(i); 	
	}
	public static int factorial(int f) 
	{
       int sonuc = 1;
       for(int i = 1; i <= f; i++) 
       {
    	   sonuc *= i; 
       }
       return sonuc;
}


    /**
     * Creates new form ayrık
     */
    public AyrıkYapılarProje2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sequence 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sequence 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sequence 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sequence 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Sequence 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Sequence 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ayrıkYapılarProje2/folder/asd.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setText(null);
        int n=Integer.parseInt(JOptionPane.showInputDialog("Enter the value of n :"));
        int sayılar[] = new int[n];
        int j = 1;
        for (int i = 0; i < sayılar.length; i++) {
             sayılar[i] = j;
             j=j+2+i;
        }
        for (int i = 0; i < sayılar.length; i++) {
            jTextArea1.setText(jTextArea1.getText()+ " " +sayılar[i]+ ",");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      jTextArea1.setText(null);
      int sayi =Integer.parseInt(JOptionPane.showInputDialog("Enter the value of n :"));
      int[] seri = new int[sayi];
      seri[0] = 1;
      for(int i=1; i < sayi; i++){      
        seri[i]=seri[i-1]+3;
      }
      for(int i=0; i< sayi; i++){    
      jTextArea1.setText(jTextArea1.getText()+ " " +seri[i]+ ",");  
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextArea1.setText(null);
        int iter = Integer.parseInt(JOptionPane.showInputDialog("Enter the value of n :"));  
             String[] sequence = new String[iter];             
             sequence = AyrıkYapılarProje2.third(iter);              
             String output = "";                       
             for (int i = 0; i < sequence.length; i++) {   
                 output = output.concat(sequence[i]);          
             }           
             jTextArea1.setText(jTextArea1.getText()+ " " +output+ ",");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jTextArea1.setText(null);
        int n =Integer.parseInt(JOptionPane.showInputDialog("Enter the value of n :"));
         if (n == 0) {
           jTextArea1.setText("0");
       } else if (n == 1) {
           jTextArea1.setText("0,1,");
       } else {
           jTextArea1.setText("0,1,");
           int a = 0;
           int b = 1;
           for (int i = 1; i < n; i++) {
               int nextNumber = a + b;
               jTextArea1.setText(jTextArea1.getText()+ " " +nextNumber+ ",");
               a = b;
               b = nextNumber;
           }
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       jTextArea1.setText(null);
        double x, n, toplam=1;
		int i;
		x = Integer.parseInt(JOptionPane.showInputDialog("Enter the value of x :"));
		n = Integer.parseInt(JOptionPane.showInputDialog("Enter the value of n :"));
      for(i = 1; i <= n-1; i++)
		{
	    	toplam += math(x,i);
                    
                jTextArea1.setText(toplam+ "");
		}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextArea1.setText(null);
        int n=Integer.parseInt(JOptionPane.showInputDialog("Enter the value of n :"));
        int x = 1;
        int carpim = 9;
        int sonuc;
        String adim;
        ArrayList seri6 = new ArrayList(n);
        for (int i = 0; i < n; i++) {
            sonuc = (x * carpim) + i + 2;
            adim = (x + "x" + carpim + "+" + (i + 2) + "=" + sonuc);
            seri6.add(adim);
            x = x + sonuc;
        }
        for (int i = 0; i < n; i++) {
           jTextArea1.append(seri6.get(i)+"\n");
        }
        
    
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AyrıkYapılarProje2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AyrıkYapılarProje2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AyrıkYapılarProje2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AyrıkYapılarProje2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AyrıkYapılarProje2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
